### ISSUE TITLE
LỖI BẢN BETA QUÁ AD ƠI 

### ISSUE THREAD

**Issue by trantrunghieu27** [catalizcs/mirai-beta#5]
![image](https://user-images.githubusercontent.com/75115578/100427275-ce6e7200-30c4-11eb-9101-07395b6885da.png)
lỗi quá ad ơi, bản beta

**Comment by spermlord** [comment]
Chụp phiên bản đang dùng
Chụp .env
Chụp file lang (dòng bạn sửa)

**Comment by Hagard-Cell** [comment]
> cho mình xin phiên bản của bản beta đó
> nó nằm ở trong package.json

Tưởng bảo nghỉ :v
Dead all mà :v

**Comment by spermlord** [comment]
> > cho mình xin phiên bản của bản beta đó
> > nó nằm ở trong package.json
> 
> Tưởng bảo nghỉ :v
> Dead all mà :v

làm gì có ai bảo nghỉ?

**Comment by catalizcs** [comment]
dead rồi nhé, do @spermlord chưa cập nhật kịp "/

**Comment by Hagard-Cell** [comment]
> > > cho mình xin phiên bản của bản beta đó
> > > nó nằm ở trong package.json
> > 
> > Tưởng bảo nghỉ :v
> > Dead all mà :v
> 
> làm gì có ai bảo nghỉ?

Tâm bảo nghỉ :v

**Comment by catalizcs** [comment]
> dead rồi nhé, do @spermlord chưa cập nhật kịp "/

^

**Comment by spermlord** [comment]
me nub

**Comment by spermlord** [comment]
Đã fix. Up lên F6 là đc nhé
