### ISSUE TITLE
mong ad thêm tính năng

### ISSUE THREAD

**Issue by votientien888** [catalizcs/mirai-beta#6]
mong ad thêm tính năng đếm số tin nhắn của tất cả thành viên trong box. và có thể cho nick bot có thể gõ lệnh.

**Comment by catalizcs** [comment]
1/ bọn mình xin lỗi bạn, việc phát triển v1 hiện tại bọn mình đang ngừng lại, tập trung cho v2
2/ nếu bạn muốn bot có thể sử dụng cả lệnh chỉ việc thay dòng `selfListen: false`  trong app/login/option thành `selfListen: true` sau đó save file lại

**Comment by votientien888** [comment]
Cảm ơn ad. Mong v2 sẽ có chức năng đếm số tin nhắn của các tv trong box (chỉ có admin box mới có thể reset bộ đếm) .
Lệnh thông báo tin nhắn gỡ. Không có liên kết khi gỡ hình ảnh. Và không thể bật tất cả các box chỉ với 1 lệnh mà phải bật từng box
